name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test Service Signatures
      run: go test -v ./.../modules/v1/utilities/signatures/service/

    - name: Test Service User
      run: go test -v ./.../modules/v1/utilities/user/service/

    - name: Test Repository Signatures
      run: go test -v ./.../modules/v1/utilities/signatures/repository/

    - name: Test Repository User
      run: go test -v ./.../modules/v1/utilities/user/repository/

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [ continuous-integration ]
    steps: 
    - uses: actions/checkout@v3
    - name: Deployment to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.APPS_HOSTNAME }}
        username: ${{ secrets.APPS_USERNAME }}
        password: ${{ secrets.APPS_PASSWORD }}
        port: ${{ secrets.APPS_PORT }}
        script: cd /root/go/src/e-signature && git pull && systemctl restart sign
